function [ax,srf,cam] = make_surface_plot(~,data,surf,pos,view,clim)
% Constructs a single axis with a hemisphere in it. Called exclusively by
% plotter. 
%
%   For more information, please consult our <a
%   href="https://brainspace.readthedocs.io/en/latest/pages/matlab_doc/visualization/plot_hemispheres.html">ReadTheDocs</a>.


ax = axes('Position',pos);
srf = trisurf(surf.tri, ...
            surf.coord(1,:), ...
            surf.coord(2,:), ...
            surf.coord(3,:), ...
            data, ...
            'EdgeColor', 'None');
material dull; lighting phong;
colormap(parula(256));

set(ax                                  , ...
    'Visible'           , 'off'         , ...
    'DataAspectRatio'   , [1 1 1]       , ...
    'PlotBoxAspectRatio', [1 1 1]       , ...
    'CLim'              , clim          , ...
    'View'              , view          );

% Add a camlight.
cam = camlight();