name: Python Code Coverage
on:
  push:
    branches:
      - 'master'

jobs:
  codecov:
    name: Codecov Workflow
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Generate coverage report
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest pytest-cov
          python3 -m pip install -r requirements.txt
          python3 -m pytest --cov=./ --cov-report=xml 
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
